### ISSUE TITLE
Scala 2.12?

### ISSUE THREAD

**Issue by ryantheleach** [Katrix-/KatLib#1]
Thanks for making this Kat, but I was just wondering, is any of this renamed when it gets added to the classpath?

Is there a way to make this, so a 2.12 version of KatLib could sit alongside 2.11 and work correctly?

2.12 while it's still in RC, and not included on Forge, has a great many additions for Java8

**Comment by Katrix** [comment]
Scala is shaded in (on of the reasons I made, it, so I could just do it once). Using another version of Scala, as long as it's shaded to somewhere else is completely fine.

**Comment by ryantheleach** [comment]
Yeah just looked at the jar, on the whole it looks good.

I was wondering though, do you expect others to use this as well? or should people shade their own copies? I get that you have other classes in here, but I'm wondering on the API stability of those classes, or should the recommendation to be that if you depend on katlib, to not use the classes other then the Scala classes?

I ask, because I'm also interested in developing with Scala, but I've not found a nice solution to sharing the same scala libs, where possible.

**Comment by Katrix** [comment]
There shouldn't be a problem for other people to use this. Once 2.12 is officially released I will update this, which will break compatibility with previous versions. The only thing you need to do is add the assembly plugin to the project, add KatLib as a provided dependecy, and add this to the shade rules.

```
assemblyShadeRules in assembly := Seq(
    ShadeRule.rename("scala.**" -> "io.github.katrix.katlib.shade.scala.@1").inProject
)
```

**Comment by ryantheleach** [comment]
Cheers, just a heads up I'm forking this for now, mainly just want to fool around with the Scala 2.12 pre-release and have a go at seeing what helpers I can make.

This isn't a slight against you, I'm really thankful for the foundation build tooling you have provided, Your helpers will probably be better then mine, but I just want to have a go to see what I can come up with.

If I end up writing any plugins written in Scala I might contribute back or use KatLib even, but for now this is just me having fun. Hope you don't mind.
